# Site settings
title: "Story Blog"
email: mk3916@columbia.edu
description: "A dark blog theme for Jekyll."
baseurl: ""
title_description: "Story blog to keep track of various elements of my writing."
title_image: "https://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
#google_analytics: 
#disqus_account: 
github_repository: https://github.com/modernAlcibiades/story-blog
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
# twitter_username: 
# github_username: modernAlcibiades
# instagram_username: 
# reddit_username: 
# linkedin_link:
# google_plus_link: 
# stackoverflow_link: 
# xing_link:
# facebook_link:

# Footer
footer_right: "&lt;/&gt; on <a href=\"https://github.com/modernAlcibiades/story-blog\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
